version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: ammukaleem/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment: 
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - vprofile-net
    restart: always  # Ensure it always restarts

  vproapp:
    build:
      context: ./Docker-files/app
    image: ammukaleem/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: ammukaleem/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
networks:
  default:
    name: mynetwork
    driver: bridge
